from pathlib import Path

import numpy as np
import torch
from torch.utils.data import Dataset


class NPZPatchDataset(Dataset):
    """Dataset for .npz files generated by dataset/build_npz_dataset.py."""

    def __init__(self, list_file, require_mask=True):
        list_path = Path(list_file)
        self.paths = [Path(line.strip()) for line in list_path.read_text(encoding="utf-8").splitlines() if line.strip()]
        self.require_mask = require_mask

    def __len__(self):
        return len(self.paths)

    def __getitem__(self, idx):
        path = self.paths[idx]
        data = np.load(path)
        image = data["image"]
        if image.ndim == 2:
            image = image[..., None]
        image = image.astype(np.float32)
        if image.max() > 1.0:
            image /= 255.0
        image = torch.from_numpy(image.transpose(2, 0, 1))

        if "mask" not in data:
            if self.require_mask:
                raise KeyError(f"{path} does not contain a mask array")
            return image, str(path)

        mask = np.clip(data["mask"].astype(np.float32), 0.0, 1.0)
        return image, torch.from_numpy(mask[None, ...])
